spring.application.name=bookstore
spring.main.banner-mode=off

spring.datasource.url=jdbc:mariadb://localhost:3306/bookstore
spring.datasource.username=admin
spring.datasource.password=admin.123
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

spring.jpa.open-in-view=false

spring.security.user.name=admin
spring.security.user.password=admin.123

app.jwt.secret=YjM2N2E5ZTU0Y2QxNDY4Y2I5N2U1NmQyZGU3ODkwYjI4ZjQzM2Q1YzA5YjE2N2E4ZmQ0YjI5YzEwZTJlM2Y0YQ==
app.jwt.expiration-ms=360000

spring.cache.type=caffeine
spring.cache.cache-names=users
