spring.application.name=bookstore
spring.main.banner-mode=off

spring.datasource.url=jdbc:mariadb://localhost:3306/bookstore
spring.datasource.username=admin
spring.datasource.password=admin.123
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create-only
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
